### ISSUE TITLE
深色模式

### ISSUE THREAD

**Issue by JustJoy122** [NXY666/EdgePolicyManager#17]
### 建议详情

晚上打开的时候快被闪瞎了
深色模式支持对于winui应该比较简单……对吧？

**Comment by NXY666** [comment]
有一个尴尬的事情，就是——我一开始就只考虑了多语言，颜色什么的全写死了（这玩意是从学C#的第一天开始写的，当时啥都不会~~现在也是~~），如果有时间的话我会尝试学着做个夜间模式
